language: ruby

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
  
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
 - bundle exec rake db:migrate
 - bundle exec rake assets:precompile
 - bundle exec rspec